name: Python Cron Runner

on:
  schedule:
    - cron: "*/10 * * * *"   # har 10 minute
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script with retry
        run: |
          ATTEMPT=0
          MAX_ATTEMPT=3

          until [ $ATTEMPT -ge $MAX_ATTEMPT ]
          do
            echo "Starting script attempt $ATTEMPT"
            python main.py && break
            ATTEMPT=$((ATTEMPT+1))
            echo "Script failed. Restarting in 10 seconds..."
            sleep 10
          done
