name: SELF RESTART BOT

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Requests
        run: pip install requests

      - name: Run Bot
        run: |
          echo "BOT RUNNING"
          END=$((SECONDS+21000))   # ~5h 50m

          while [ $SECONDS -lt $END ]; do
            python main.py
            sleep 3
          done

      - name: Restart Workflow
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/run.yml/dispatches \
          -d '{"ref":"main"}'
